uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    tag: "1.23.16-debian"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: letsencrypt-ionos-staging
    hosts:
      - host: uptime-kuma.local.ibartels.de
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: uptime-kuma-tls
        hosts:
          - uptime-kuma.local.ibartels.de