uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    tag: "1.23.16-debian"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: letsencrypt-ionos-pro
    hosts:
      - host: uptime-kuma.local.ibartels.de
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: uptime-kuma-cert-tls
        hosts:
          - uptime-kuma.local.ibartels.de
  persistence:
    data:
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      skipuninstall: true
      size: "5Gi"
      mountPath: /app/data
      enabled: true
