uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    tag: "1.23.16-debian"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: uptime-kuma.local.ibartels.de
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: local.ibartels.de-tls
        hosts:
          - uptime-kuma.local.ibartels.de