repo:
  url: https://github.com/Puller23/k8s-gitops.git
  revision: main

applications:
  - name: homelab
    namespace: argocd
    path: main/homelab
    manifest-paths: /main/homelab/templates;/main/homelab/Chart.yaml;/main/homelab/values.yaml
    sync-wave: "-1"
    helm:
      enabled: true
  - name: monitoring
    namespace: monitoring
    path: main/monitoring
    manifest-paths: /main/monitoring/templates;/main/monitoring/Chart.yaml;/main/monitoring/values.yaml
    sync-wave: "-2"
    helm:
      enabled: true

