---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-emqx-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-homelab
    kind: SecretStore 
  target:
    name: emqx-secrets
  data:
    - secretKey: EMQX_AUTH__USER__1__PASSWORD
      remoteRef:
        key: kv/homelab/emqx
        property: EMQX_AUTH__USER__1__PASSWORD
    - secretKey: EMQX_AUTH__USER__1__USERNAME
      remoteRef:
        key: kv/homelab/emqx
        property: EMQX_AUTH__USER__1__USERNAME
    - secretKey: EMQX_AUTH__USER__2__PASSWORD
      remoteRef:
        key: kv/homelab/emqx
        property: EMQX_AUTH__USER__2__PASSWORD
    - secretKey: EMQX_AUTH__USER__2__USERNAME
      remoteRef:
        key: kv/homelab/emqx
        property: EMQX_AUTH__USER__2__USERNAME
    - secretKey: EMQX_DASHBOARD__DEFAULT_PASSWORD
      remoteRef:
        key: kv/homelab/emqx
        property: EMQX_DASHBOARD__DEFAULT_PASSWORD