---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cert-webhook-ionos-secrets
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-k8s-cert-webhook-ionos
    kind: SecretStore 
  target:
    name: cert-webhook-ionos-secrets
  data:
    - secretKey: IONOS_PUBLIC_PREFIX
      remoteRef:
        key: kv/k8s/ionos/cert-webhook
        property: IONOS_PUBLIC_PREFIX
    - secretKey: IONOS_SECRET
      remoteRef:
        key: kv/k8s/ionos/cert-webhook
        property: IONOS_SECRET