---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-ibartels-de
  namespace: cert-manager
spec:
  dnsNames:
    - '*.home.ibartels.de'
  issuerRef:
    name: letsencrypt-ionos-prod
  secretName: home-ibartels-de-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "homelab,monitoring,longhorn-system,argocd"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "homelab,monitoring,longhorn-system,argocd" # Control auto-reflection namespaces
