longhorn:
  persistence:
    defaultClassReplicaCount: 3
  defaultSettings:
    defaultReplicaCount: 3
    createDefaultDiskLabeledNodes: true
    backupTarget: nfs://10.18.20.20:/mnt/data/nfs/longhorn
    storageMinimalAvailablePercentage: "10"
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    defaultDataPath: /var/mnt/longhorn
    defaultLonghornStaticStorageClass: longhorn
  ingress:
    enabled: false
    host: longhorn.local.ibartels.de
    tlsSecret: longhorn-tls-prod
    tls: true
    annotations:
      cert-manager.io/issuer: letsencrypt-ionos-prod
  preUpgradeChecker:
    # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
    jobEnabled: false
    # -- Setting that allows Longhorn to perform upgrade version checks after starting the Longhorn Manager DaemonSet Pods. Disabling this setting also disables `preUpgradeChecker.jobEnabled`. Longhorn recommends keeping this setting enabled.
    upgradeVersionCheck: false
  longhornUI:
    replicas: 1
  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    provisionerReplicaCount: 1
    snapshotterReplicaCount: 1