longhorn:
  persistence:
    defaultClassReplicaCount: 1
  defaultSettings:
    defaultReplicaCount: 1
    createDefaultDiskLabeledNodes: true
    backupTarget: nfs://nas.local.ibartels.de/data/nfs/longhorn
    storageMinimalAvailablePercentage: "10"
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    defaultDataPath: /var/lib/longhorn
    defaultLonghornStaticStorageClass: longhorn
  ingress:
    enabled: true
    host: longhorn.local.ibartels.de
    tlsSecret: longhorn-tls-prod
    tls: true
    annotations:
      cert-manager.io/issuer: letsencrypt-ionos-prod
  preUpgradeChecker:
    # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
    jobEnabled: false
    # -- Setting that allows Longhorn to perform upgrade version checks after starting the Longhorn Manager DaemonSet Pods. Disabling this setting also disables `preUpgradeChecker.jobEnabled`. Longhorn recommends keeping this setting enabled.
    upgradeVersionCheck: false