---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-influxdb2-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-monitoring
    kind: SecretStore 
  target:
    name: influxdb-secrets
  data:
    - secretKey: admin-password
      remoteRef:
        key: kv/k8s/monitoring/influxdb
        property: admin-password
    - secretKey: admin-token
      remoteRef:
        key: kv/k8s/monitoring/influxdb
        property: admin-token
        