---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-home-assistant-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-homelab
    kind: SecretStore 
  target:
    name: home-assistant-secrets
  data:
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
    - secretKey: HASS_FREEATHOME_PASSWORD
      remoteRef:
        key: kv/homelab/home-assistant
        property: HASS_FREEATHOME_PASSWORD
        