homepage:
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v0.10.9

  resources:
    requests:
      cpu: 15m
      memory: 127M
    limits:
      memory: 308M
  
  config:
    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:
      layout:
        Home:
          style: row
          columns: 6
        Tools:
          style: row
          columns: 6
        Infrastructure:
          style: row
          columns: 3
        Monitoring:
          style: row
          columns: 3
      background:
        image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
        blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
        saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
        brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
        opacity: 50 # 0-100
  env:
    TZ: Europe/Berlin