emqx:
  replicaCount: 2
  recreatePods: true
  service:
    type: LoadBalancer
    loadBalancerIP: 10.18.20.42
  envFromSecret: "emqx-secrets"
  emqxConfig:
    EMQX_ALLOW_ANONYMOUS: "false"
    EMQX_LOADED_MODULES: "emqx_mod_presence,emqx_mod_acl_internal,emqx_mod_topic_metrics"
    EMQX_LOADED_PLUGINS: "emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_rule_engine,emqx_auth_mnesia,emqx_prometheus"
    EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
  emqxAclConfig: >
    {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
    {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
    {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
    {allow, all}.
  resources:
    limits:
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    dashboard:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: emqx
        gethomepage.dev/name: EMQX
      path: /
      hosts:
        - emqx.home.ibartels.de
      tls:
        - hosts:
            - emqx.home.ibartels.de
          secretName: home-ibartels-de-tls
