---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-homelab
  namespace: homelab
spec:
  provider:
    vault:
      server: "http://10.18.20.21:8200"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token-homelab"
          key: "token"