---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-k8s-cert-webhook-ionos
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "https://vault.local.ibartels.de"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token-k8s-cert-webhook-ionos"
          key: "token"