repo:
  url: https://github.com/Puller23/k8s-gitops.git
  revision: main

applications:
  - name: gethomepage
    namespace: homelab
    path: main/homelab/gethomepage
    manifest-paths: /main/homelab/gethomepage
    sync-wave: "-1"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  - name: home-assistant
    namespace: homelab
    path: main/homelab/home-assistant
    manifest-paths: /main/homelab/home-assistant
    sync-wave: "-1"
    helm:
      enabled: true
  - name: node-red
    namespace: homelab
    path: main/homelab/node-red
    manifest-paths: /main/homelab/node-red
    sync-wave: "-1"
    helm:
      enabled: true