argo-cd:
  dex:
    enabled: false

  repoServer:
    autoscaling:
      enabled: false

    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: 300s

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false


    resources:
      requests:
        cpu: 1000m
        memory: 2048Mi
      limits:
        cpu: 2000m
        memory: 2048Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: storage
                  operator: DoesNotExist
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-repo-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - repo-server
            topologyKey: "kubernetes.io/hostname"

  server:
    logLevel: debug
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: argocd.png
        gethomepage.dev/name: ArgoCD
        kubernetes.io/ingress.class: nginx
      hostname: argocd.home.ibartels.de
      hosts:
        - argocd.home.ibartels.de
      tls:
        - hosts:
            - "argocd.home.ibartels.de"
          secretName: home-ibartels-de-tls
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/Puller23/k8s-gitops.git
      # Following the guide at https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle

    autoscaling:
      enabled: true
      minReplicas: 1
      targetCPUUtilizationPercentage: 65
      targetMemoryUtilizationPercentage: 65
    resources:
      requests:
        cpu: 500m
        memory: 180Mi
      limits:
        cpu: 500m
        memory: 200Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - server
            topologyKey: "kubernetes.io/hostname"

  controller:
    replicas: 1

    args:
      repoServerTimeoutSeconds: 300
  redis:
    # -- Enable redis
    enabled: true
    # -- Redis name
    name: redis
    image:
      # -- Redis tag
      tag: 7.0.7-alpine