repo:
  url: https://github.com/Puller23/k8s-gitops.git
  revision: main

applications:
  - name: external-secrets
    namespace: kube-system
    path: infrastructure/external-secrets
    manifest-paths: /infrastructure/external-secrets
    sync-wave: "-4"
    helm:
      enabled: true
  - name: ingress-nginx
    namespace: kube-system
    path: infrastructure/ingress-nginx
    manifest-paths: /infrastructure/ingress-nginx
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  - name: metallb
    namespace: kube-system
    path: infrastructure/metallb
    manifest-paths: /infrastructure/metallb
    sync-wave: "-4"
    helm:
      enabled: true
  - name: cert-manager
    namespace: cert-manager
    path: infrastructure/cert-manager
    manifest-paths: /infrastructure/cert-manager
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  - name: cert-manager-webhook-ionos
    namespace: cert-manager
    path: infrastructure/cert-manager-webhook-ionos
    manifest-paths: /infrastructure/cert-manager-webhook-ionos
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  - name: longhorn
    namespace-sync-wave: "-4"
    namespace: longhorn-system
    path: infrastructure/longhorn
    manifest-paths: /infrastructure/longhorn
    sync-wave: "-3"
    helm:
      enabled: true