---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-paperless-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-homelab
    kind: SecretStore 
  target:
    name: paperless-secrets
  data:
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_ADMIN_PASSWORD
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_ADMIN_USER
    - secretKey: PAPERLESS_DBHOST
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_DBHOST
    - secretKey: PAPERLESS_DBNAME
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_DBNAME
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_DBPASS
    - secretKey: PAPERLESS_DBPORT
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_DBPORT
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_DBUSER
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: kv/homelab/paperless
        property: PAPERLESS_SECRET_KEY
        