---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-grafana-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-monitoring
    kind: SecretStore 
  target:
    name: grafana-secrets
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: kv/k8s/monitoring/grafana
        property: GF_SECURITY_ADMIN_PASSWORD
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: kv/k8s/monitoring/grafana
        property: GF_SECURITY_ADMIN_USER
        